### ISSUE TITLE
Compiling !!!!

### ISSUE THREAD

**Issue by MSF-Jarvis** [TeamRedux/ApkTool-Wrapper-Scripts#1]
The compile.sh scripts doesn't compile apks successfully because of a faulty apktool reference.
Looking into a solution.

**Comment by MSF-Jarvis** [comment]
Hey @faddat, can you figure out a way to fix this issue. It's in the compile.sh script cause i can't get the script to automatically attach the name of the only folder inside that directory to the apktool b   command

**Comment by faddat** [comment]
Probably...
 After k8s though.... :/ (so tired of the cloud)(yet love the cloud so much!)

**Comment by MSF-Jarvis** [comment]
No problem, this is secondary to AAC-Redux after all.
